### ISSUE TITLE
Add the quantity value to Weapons and Armor

### ISSUE THREAD

**Issue by Cup-of-Coffee** [Spice-King/foundry-swnr#84] opened 2022-07-11 02:03 UTC
Currently the only way for a character sheet to hold several quantities of the same type of armor is to have multiple instances take up space. 

![Screenshot 2022-07-10 215527](https://user-images.githubusercontent.com/39238717/178174280-a561f272-6207-408e-bfb8-aa0e09f3eb46.png)

In the example above, you have a character holding three chaincutters, 3 combat field uniforms and 7 biofuel tanks. Unlike the biofuel tanks, you can only show a character having multiple items of the same the weapons and armor is to have it take up a significant amount of sheet space. 

A possibly quick and simple fix is to add the quantity value to the weapons and armor classes, and only have one include it's enc for Readied when readied, the rest of the enc from the other weapons/armors going to Stowed (and if stowed away, have all count it's enc to Stowed).

**Comment by Spice-King** [comment] 2022-07-12 02:55
Short answer is going to be no for adding a quantity to equip-able items and *probably* also a no for trying to make smart auto stacking/collapsible groups. The first does have a technical reasons, the later is I'd rather spend my very limited time elsewhere, of which this response to this issue already kind of consumed most of today's free time.

General items (field radios, metatools, thermal flairs, rations, and so on) are generally all fungible, one unit of spare parts is the same as another for any case, same could be said for many items. They only got quantities to deal with item bundles as any one of them in a bundle were again functionally the same. General items, at least in my admittedly limited experience, is that general items are rarely the target of PC's modding, though I could easily see someone mod a storage unit to be concealed or something for a data heist.

Weapons and armor have more "per instance" data that does not make much sense in the concept of a "stack" of the same item. Weapons have ammo tracking, armor has the concept of tracking if it's counted as equipped, neither of which makes much sense once made to track an over all quantity of said item, while throwing a wrench into ammo tracking for weapons. This also would mess with plans of FVTT's Active Effects and SWNR's item modding, though it's probably easiest to just flat ignore the quantity.

---

Now on to what I *do* consider to be the "right" solution, trying to figure out how to automatically group copies of the same item together and render in a collapsible way. One could opt to do a deep compare of the source data, but the unique IDs of the items' themselves fail that. Ignore the items' own ID then? The Active Effects on the items also have unique IDs and would fail comparison. Ignore that? OK, the effects collection is ordered, and each change is ordered too, all of which may or may not have a net effect if the order differs on any of that (depending on the changes applied, what order they are applied could dramatically change the end value (x2 then +5 differs from +5 then x2, but a +1 and a +2 does not matter in the order). Someone is going to find a way to make both reordering and not wrong and be mad about it.

Skipping the wrench that is effects, I'm also going to expect people to get mad if I'm either super strict on making sure it's perfectly strictly the same items in the end if TinyMCE was to make a invincible difference that functionally looks the same or if I allow some slight fuzzy matching and the threshold ends up just high enough to stack together two items that should not be. Do I expect SWNR players/GMs to get mad about that, no I do think the community is healthier than that, but then I've been helping with putting out small fires caused by SWADE users who absolutely would, so I've had my views of the public have tempered some. Then we get to the UI issues with quick access things to items, things like inventory state, equipped status, even edit and delete buttons.

So yea, to do it right would be a headache to some the programmatic problems, has good odds of making some percentage of users mad somehow, and feels like a very low return on my limited development time. Trying to make a shortcut would either be buggy as hell, make far more people mad, or my personal favorite, both of those at once. As much as I'd see the value of implementing it, there are other things that have a much higher priority to work on. Few of which I have a degree of personal motivation to work on them, a small win in these times.

Closing for now, might revisit if somehow I have much more free time than I do now.

**Closed by Spice-King** 2022-07-12 02:55 UTC
