### ISSUE TITLE
"Dice Pool" and "Stats" drop-down menus

### ISSUE THREAD

**Issue by aquafraternal** [Spice-King/foundry-swnr#50] opened 2021-06-06 09:34 UTC
"Dice Pool" and "Stats" drop-down menus are greyed-out when you attempt to roll a skill, so you're not able to select the proper attribute or adjust the dice pool.  The default entries (2d6 and Strength) apply correctly, but cannot be modified.

**Comment by Spice-King** [comment] 2021-06-06 18:08
Duplicate of #40. Please do double check even the closed issues for your issues in the future.

**Closed by Spice-King** 2021-06-06 18:08 UTC
Labels: duplicate

**Comment by aquafraternal** [comment] 2021-06-06 20:57
Sorry! 🤦🏼‍♂️ I’d been surprised to not see it already reported. Thanks for the advice.
